## Numerical differentiation
Recall that the limit as h approaches 0 of (cos(1+h)-cos(1))/h -> -sin(1)
  

In [6]:
import math, numpy as np, matplotlib.pyplot as plt

In [7]:
h = 1e-5

In [8]:
(math.cos(1.+h)-math.cos(1.))/h

-0.8414736863082694

In [10]:
-math.sin(1)

-0.8414709848078965

In [11]:
h = 2**-52

In [12]:
(math.cos(1.+h)-math.cos(1.))/h

-1.0

In [13]:
h = 2**-53
(1+h).hex()

'0x1.0000000000000p+0'

In [14]:
(math.cos(1.+h)-math.cos(1.))/h

0.0

In [20]:
h = np.logspace(-1,-17,17)
h

array([1.e-01, 1.e-02, 1.e-03, 1.e-04, 1.e-05, 1.e-06, 1.e-07, 1.e-08,
       1.e-09, 1.e-10, 1.e-11, 1.e-12, 1.e-13, 1.e-14, 1.e-15, 1.e-16,
       1.e-17])

In [21]:
(1+h)[-1],(1+h)[-2],(1+h[-3]) #We can see that the third last entry does not round down to 1

(1.0, 1.0, 1.000000000000001)

In [22]:
np.cos(1+h)

array([0.45359612, 0.53186072, 0.53946056, 0.54021816, 0.54029389,
       0.54030146, 0.54030222, 0.5403023 , 0.54030231, 0.54030231,
       0.54030231, 0.54030231, 0.54030231, 0.54030231, 0.54030231,
       0.54030231, 0.54030231])

In [26]:
est = (np.cos(1+h) - np.cos(1))/h
est

array([-0.86706184, -0.84415845, -0.841741  , -0.841498  , -0.84147369,
       -0.84147125, -0.84147101, -0.84147098, -0.84147112, -0.84147134,
       -0.84147134, -0.84154905, -0.84043883, -0.8437695 , -0.88817842,
        0.        ,  0.        ])

In [27]:
err = est - (-math.sin(1))
err

array([-2.55908596e-02, -2.68746457e-03, -2.70010885e-04, -2.70137126e-05,
       -2.70150037e-06, -2.70089745e-07, -2.80611252e-08,  3.02511949e-09,
       -1.30201643e-07, -3.52246248e-07, -3.52246248e-07, -7.80678580e-05,
        1.03215517e-03, -2.29851391e-03, -4.67074349e-02,  8.41470985e-01,
        8.41470985e-01])

In [28]:
for hk,estk,errk in zip(h,est,err):
    print(hk,estk,errk)

0.1 -0.8670618444256245 -0.025590859617728
0.01 -0.8441584493784293 -0.002687464570532816
0.001 -0.8417409956931188 -0.00027001088522227157
0.0001 -0.8414979985205129 -2.7013712616374974e-05
1e-05 -0.8414736863082694 -2.701500372848109e-06
1e-06 -0.8414712548976411 -2.7008974456954604e-07
1e-07 -0.8414710128690217 -2.8061125201261916e-08
1e-08 -0.841470981782777 3.025119488242467e-09
1e-09 -0.84147111500954 -1.3020164346677632e-07
1e-10 -0.8414713370541449 -3.522462483918076e-07
1e-11 -0.8414713370541449 -3.522462483918076e-07
1e-12 -0.8415490526658687 -7.806785797215277e-05
1e-13 -0.8404388296412435 0.0010321551666530038
1e-14 -0.843769498715119 -0.002298513907222466
1e-15 -0.8881784197001251 -0.046707434892228616
1e-16 0.0 0.8414709848078965
1e-17 0.0 0.8414709848078965


In [30]:
'%e %e $%e' % (hk, estk, errk)

'1.000000e-17 0.000000e+00 $8.414710e-01'

In [31]:
f'with h = {hk} the derivative estimate is {estk} with error {errk}'

'with h = 1e-17 the derivative estimate is 0.0 with error 0.8414709848078965'

In [33]:
f'with h = {hk:5.0e} the derivative estimate is {estk:20.17f} with error {errk:.17g}'

'with h = 1e-17 the derivative estimate is  0.00000000000000000 with error 0.8414709848078965'

In [39]:
for hk,estk,errk in zip(h,est,err):
    print(f'with h = {hk:5.0e} the derivative estimate is {estk:20.17f} with error {errk:20.17f}')

with h = 1e-01 the derivative estimate is -0.86706184442562451 with error -0.02559085961772800
with h = 1e-02 the derivative estimate is -0.84415844937842932 with error -0.00268746457053282
with h = 1e-03 the derivative estimate is -0.84174099569311878 with error -0.00027001088522227
with h = 1e-04 the derivative estimate is -0.84149799852051288 with error -0.00002701371261637
with h = 1e-05 the derivative estimate is -0.84147368630826935 with error -0.00000270150037285
with h = 1e-06 the derivative estimate is -0.84147125489764107 with error -0.00000027008974457
with h = 1e-07 the derivative estimate is -0.84147101286902171 with error -0.00000002806112520
with h = 1e-08 the derivative estimate is -0.84147098178277702 with error  0.00000000302511949
with h = 1e-09 the derivative estimate is -0.84147111500953997 with error -0.00000013020164347
with h = 1e-10 the derivative estimate is -0.84147133705414490 with error -0.00000035224624839
with h = 1e-11 the derivative estimate is -0.84147

In [41]:
hpt = 2 * 2**-26 
hpt

2.9802322387695312e-08

In [46]:
f'{(math.cos(1+hpt) - math.cos(1))/hpt + math.sin(1):20.17f}'

'-0.00000000924737464'